//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawBringer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassroomCourse
    {
        public string ClassroomRoomNumber { get; set; }
        public string CourseName { get; set; }
        public string DayOfWeek { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual Course Course { get; set; }
    }
}
