//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawBringer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LawyerTimeSlot
    {
        public int LawyerID { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Lawyer Lawyer { get; set; }
    }
}
